services:
  receiptprocessor:
    image: receiptprocessor
    build:
      context: .
      dockerfile: ReceiptProcessor/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development